version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27020:27019"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./logs:/var/log/mongodb
volumes:
  mongo-data: